### ISSUE TITLE
install error on TrueNAS Scale bulid

### ISSUE THREAD

**Issue by SavageSalem** [wolveix/satisfactory-server#247]
Hi there,
total noob here, hitting a wall.

keep getting this Error when installing from the TrueCharts Catalog
Googled the error message and looked on the TrueCharts Discord. 
couldnt really see anything relavent to satisfactory.

i7-4770 CPU
RAM 16GB
TrueNAS-SCALE-22.12-RC.1

```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 461, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1152, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1284, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 479, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1306, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1266, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1169, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 44, in helm_action
    raise CallError(f'Failed to {tn_action} chart release: {stderr.decode()}')
middlewared.service_exception.CallError: [EFAULT] Failed to install chart release: Error: INSTALLATION FAILED: parse error at (satisfactory/charts/common/templates/lib/pod/_volumes.tpl:103): function "break" not defined
```

**Comment by wolveix** [comment]
Hey @SavageSalem!

I don't maintain that chart unfortunately, but it seems to be either an environment issue, or an issue with the chart. It's hard to say based off of that error alone, but Python isn't used whatsoever in this repo so unfortunately I doubt I'd be able to help much!
